import { Container } from 'inversify';
import {
  AchievementRepository,
  CommunityGroupAdminRepository,
  CommunityGroupRepository,
  CompetitionOrganizerTypeRepository,
  CompetitionOutputRepository,
  CompetitionRankRepository,
  CompetitionScaleRepository,
  CompetitionTeamTypeRepository,
  CompetitionTimeRangeRepository,
  CompetitionRepository,
  CoreTeamDivisionRepository,
  CoreTeamRepository,
  DegreeRepository,
  FacultyRepository,
  FundApplicationRepository,
  GroupRepository,
  InternalRepository,
  MajorRepository,
  PermissionRepository,
  PersonaRepository,
  ProjectGalleryRepository,
  TeamRepository,
  TestimonialRepository,
  UserRepository,
  UserPermissionRepository,
  AuthRepository,
} from '@app/domain/repositories';
import {
  AchievementRepositoryImpl,
  CommunityGroupAdminRepositoryImpl,
  CommunityGroupRepositoryImpl,
  CompetitionOrganizerTypeRepositoryImpl,
  CompetitionOutputRepositoryImpl,
  CompetitionRankRepositoryImpl,
  CompetitionScaleRepositoryImpl,
  CompetitionTeamTypeRepositoryImpl,
  CompetitionTimeRangeRepositoryImpl,
  CompetitionRepositoryImpl,
  CoreTeamDivisionRepositoryImpl,
  CoreTeamRepositoryImpl,
  DegreeRepositoryImpl,
  FacultyRepositoryImpl,
  FundApplicationRepositoryImpl,
  GroupRepositoryImpl,
  InternalRepositoryImpl,
  MajorRepositoryImpl,
  PermissionRepositoryImpl,
  PersonaRepositoryImpl,
  ProjectGalleryRepositoryImpl,
  TeamRepositoryImpl,
  TestimonialRepositoryImpl,
  UserRepositoryImpl,
  UserPermissionRepositoryImpl,
  AuthRepositoryImpl,
} from '@app/infrastructure/repositories';
import {
  CreateAchievement,
  CreateCommunityGroupAdmin,
  CreateCoreTeam,
  CreateFundApplication,
  CreateGroup,
  CreatePermission,
  CreateProjectGallery,
  CreateTeam,
  CreateTestimonial,
  CreateUser,
  DeleteUser,
  GetAchievements,
  GetCommunityGroupAdmins,
  GetCommunityGroups,
  GetCompetitions,
  GetCompetitionOutputs,
  GetCompetitionRanks,
  GetCompetitionScales,
  GetCompetitionTeamTypes,
  GetCompetitionTimeRanges,
  GetCoreTeams,
  GetFaculties,
  GetFundApplications,
  GetGroups,
  GetMajors,
  GetPermissions,
  GetProjectGalleries,
  GetSidebarExtendedState,
  GetTeams,
  GetTestimonials,
  GetUsers,
  SetSidebarExtendedState,
  UpdateAchievement,
  UpdateCommunityGroupAdmin,
  UpdateCoreTeam,
  UpdateFundApplication,
  UpdateGroup,
  UpdatePermission,
  UpdateProjectGallery,
  UpdateTeam,
  UpdateTestimonial,
  UpdateUser,
  Login,
  Logout,
} from '@app/application';
import {
  AuthClientDataSource,
  authClientDataSourceImpl,
  InfinityApiDataSource,
  infinityApiDataSourceImpl,
  SessionStorageDataSource,
  SessionStorageDataSourceImpl,
} from '@app/infrastructure/datasources/client';
import { SYMBOLS } from '@config';

export const clientContainer = new Container();

// Use cases
clientContainer.bind<CreateAchievement>(SYMBOLS.CreateAchievement).to(CreateAchievement);
clientContainer
  .bind<CreateCommunityGroupAdmin>(SYMBOLS.CreateCommunityGroupAdmin)
  .to(CreateCommunityGroupAdmin);
clientContainer.bind<CreateCoreTeam>(SYMBOLS.CreateCoreTeam).to(CreateCoreTeam);
clientContainer
  .bind<CreateFundApplication>(SYMBOLS.CreateFundApplication)
  .to(CreateFundApplication);
clientContainer.bind<CreateGroup>(SYMBOLS.CreateGroup).to(CreateGroup);
clientContainer.bind<CreatePermission>(SYMBOLS.CreatePermission).to(CreatePermission);
clientContainer.bind<CreateProjectGallery>(SYMBOLS.CreateProjectGallery).to(CreateProjectGallery);
clientContainer.bind<CreateTeam>(SYMBOLS.CreateTeam).to(CreateTeam);
clientContainer.bind<CreateTestimonial>(SYMBOLS.CreateTestimonial).to(CreateTestimonial);
clientContainer.bind<CreateUser>(SYMBOLS.CreateUser).to(CreateUser);
clientContainer.bind<DeleteUser>(SYMBOLS.DeleteUser).to(DeleteUser);
clientContainer.bind<GetAchievements>(SYMBOLS.GetAchievements).to(GetAchievements);
clientContainer
  .bind<GetCommunityGroupAdmins>(SYMBOLS.GetCommunityGroupAdmins)
  .to(GetCommunityGroupAdmins);
clientContainer.bind<GetCommunityGroups>(SYMBOLS.GetCommunityGroups).to(GetCommunityGroups);
clientContainer.bind<GetCompetitions>(SYMBOLS.GetCompetitions).to(GetCompetitions);
clientContainer
  .bind<GetCompetitionOutputs>(SYMBOLS.GetCompetitionOutputs)
  .to(GetCompetitionOutputs);
clientContainer.bind<GetCompetitionRanks>(SYMBOLS.GetCompetitionRanks).to(GetCompetitionRanks);
clientContainer.bind<GetCompetitionScales>(SYMBOLS.GetCompetitionScales).to(GetCompetitionScales);
clientContainer
  .bind<GetCompetitionTeamTypes>(SYMBOLS.GetCompetitionTeamTypes)
  .to(GetCompetitionTeamTypes);
clientContainer
  .bind<GetCompetitionTimeRanges>(SYMBOLS.GetCompetitionTimeRanges)
  .to(GetCompetitionTimeRanges);
clientContainer.bind<GetCoreTeams>(SYMBOLS.GetCoreTeams).to(GetCoreTeams);
clientContainer.bind<GetFaculties>(SYMBOLS.GetFaculties).to(GetFaculties);
clientContainer.bind<GetFundApplications>(SYMBOLS.GetFundApplications).to(GetFundApplications);
clientContainer.bind<GetGroups>(SYMBOLS.GetGroups).to(GetGroups);
clientContainer.bind<GetMajors>(SYMBOLS.GetMajors).to(GetMajors);
clientContainer.bind<GetPermissions>(SYMBOLS.GetPermissions).to(GetPermissions);
clientContainer.bind<GetProjectGalleries>(SYMBOLS.GetProjectGalleries).to(GetProjectGalleries);
clientContainer
  .bind<GetSidebarExtendedState>(SYMBOLS.GetSidebarExtendedState)
  .to(GetSidebarExtendedState);
clientContainer.bind<GetTeams>(SYMBOLS.GetTeams).to(GetTeams);
clientContainer.bind<GetTestimonials>(SYMBOLS.GetTestimonials).to(GetTestimonials);
clientContainer.bind<GetUsers>(SYMBOLS.GetUsers).to(GetUsers);
clientContainer.bind<Login>(SYMBOLS.Login).to(Login);
clientContainer.bind<Logout>(SYMBOLS.Logout).to(Logout);
clientContainer
  .bind<SetSidebarExtendedState>(SYMBOLS.SetSidebarExtendedState)
  .to(SetSidebarExtendedState);
clientContainer.bind<UpdateAchievement>(SYMBOLS.UpdateAchievement).to(UpdateAchievement);
clientContainer
  .bind<UpdateCommunityGroupAdmin>(SYMBOLS.UpdateCommunityGroupAdmin)
  .to(UpdateCommunityGroupAdmin);
clientContainer.bind<UpdateCoreTeam>(SYMBOLS.UpdateCoreTeam).to(UpdateCoreTeam);
clientContainer
  .bind<UpdateFundApplication>(SYMBOLS.UpdateFundApplication)
  .to(UpdateFundApplication);
clientContainer.bind<UpdateGroup>(SYMBOLS.UpdateGroup).to(UpdateGroup);
clientContainer.bind<UpdatePermission>(SYMBOLS.UpdatePermission).to(UpdatePermission);
clientContainer.bind<UpdateProjectGallery>(SYMBOLS.UpdateProjectGallery).to(UpdateProjectGallery);
clientContainer.bind<UpdateTeam>(SYMBOLS.UpdateTeam).to(UpdateTeam);
clientContainer.bind<UpdateTestimonial>(SYMBOLS.UpdateTestimonial).to(UpdateTestimonial);
clientContainer.bind<UpdateUser>(SYMBOLS.UpdateUser).to(UpdateUser);

// Repositories
clientContainer
  .bind<AchievementRepository>(SYMBOLS.AchievementRepository)
  .to(AchievementRepositoryImpl);
clientContainer.bind<AuthRepository>(SYMBOLS.AuthRepository).to(AuthRepositoryImpl);
clientContainer
  .bind<CommunityGroupAdminRepository>(SYMBOLS.CommunityGroupAdminRepository)
  .to(CommunityGroupAdminRepositoryImpl);
clientContainer
  .bind<CommunityGroupRepository>(SYMBOLS.CommunityGroupRepository)
  .to(CommunityGroupRepositoryImpl);
clientContainer
  .bind<CompetitionOrganizerTypeRepository>(SYMBOLS.CompetitionOrganizerTypeRepository)
  .to(CompetitionOrganizerTypeRepositoryImpl);
clientContainer
  .bind<CompetitionOutputRepository>(SYMBOLS.CompetitionOutputRepository)
  .to(CompetitionOutputRepositoryImpl);
clientContainer
  .bind<CompetitionRankRepository>(SYMBOLS.CompetitionRankRepository)
  .to(CompetitionRankRepositoryImpl);
clientContainer
  .bind<CompetitionScaleRepository>(SYMBOLS.CompetitionScaleRepository)
  .to(CompetitionScaleRepositoryImpl);
clientContainer
  .bind<CompetitionTeamTypeRepository>(SYMBOLS.CompetitionTeamTypeRepository)
  .to(CompetitionTeamTypeRepositoryImpl);
clientContainer
  .bind<CompetitionTimeRangeRepository>(SYMBOLS.CompetitionTimeRangeRepository)
  .to(CompetitionTimeRangeRepositoryImpl);
clientContainer
  .bind<CompetitionRepository>(SYMBOLS.CompetitionRepository)
  .to(CompetitionRepositoryImpl);
clientContainer
  .bind<CoreTeamDivisionRepository>(SYMBOLS.CoreTeamDivisionRepository)
  .to(CoreTeamDivisionRepositoryImpl);
clientContainer.bind<CoreTeamRepository>(SYMBOLS.CoreTeamRepository).to(CoreTeamRepositoryImpl);
clientContainer.bind<DegreeRepository>(SYMBOLS.DegreeRepository).to(DegreeRepositoryImpl);
clientContainer.bind<InternalRepository>(SYMBOLS.InternalRepository).to(InternalRepositoryImpl);
clientContainer.bind<FacultyRepository>(SYMBOLS.FacultyRepository).to(FacultyRepositoryImpl);
clientContainer
  .bind<FundApplicationRepository>(SYMBOLS.FundApplicationRepository)
  .to(FundApplicationRepositoryImpl);
clientContainer.bind<GroupRepository>(SYMBOLS.GroupRepository).to(GroupRepositoryImpl);
clientContainer.bind<MajorRepository>(SYMBOLS.MajorRepository).to(MajorRepositoryImpl);
clientContainer
  .bind<PermissionRepository>(SYMBOLS.PermissionRepository)
  .to(PermissionRepositoryImpl);
clientContainer.bind<PersonaRepository>(SYMBOLS.PersonaRepository).to(PersonaRepositoryImpl);
clientContainer
  .bind<ProjectGalleryRepository>(SYMBOLS.ProjectGalleryRepository)
  .to(ProjectGalleryRepositoryImpl);
clientContainer.bind<TeamRepository>(SYMBOLS.TeamRepository).to(TeamRepositoryImpl);
clientContainer
  .bind<TestimonialRepository>(SYMBOLS.TestimonialRepository)
  .to(TestimonialRepositoryImpl);
clientContainer.bind<UserRepository>(SYMBOLS.UserRepository).to(UserRepositoryImpl);
clientContainer
  .bind<UserPermissionRepository>(SYMBOLS.UserPermissionRepository)
  .to(UserPermissionRepositoryImpl);

// Data sources
clientContainer
  .bind<AuthClientDataSource>(SYMBOLS.AuthDataSource)
  .toConstantValue(authClientDataSourceImpl);
clientContainer
  .bind<InfinityApiDataSource>(SYMBOLS.InfinityApiDataSource)
  .toConstantValue(infinityApiDataSourceImpl);
clientContainer
  .bind<SessionStorageDataSource>(SYMBOLS.SessionStorageDataSource)
  .to(SessionStorageDataSourceImpl);
