import 'reflect-metadata';
import { AuthController, AuthControllerImpl } from '@app/presentation/controllers';
import {
  AchievementRepository,
  AuthRepository,
  CommunityGroupAdminMemberRepository,
  CommunityGroupAdminRepository,
  CommunityGroupMemberRepository,
  CommunityGroupRepository,
  CompetitionInstanceRepository,
  CompetitionOrganizerTypeRepository,
  CompetitionOutputRepository,
  CompetitionRankRepository,
  CompetitionScaleRepository,
  CompetitionTeamTypeRepository,
  CompetitionTimeRangeRepository,
  CompetitionRepository,
  CoreTeamDivisionRepository,
  CoreTeamMemberRepository,
  CoreTeamRepository,
  DegreeRepository,
  FacultyRepository,
  FundApplicationRepository,
  GroupPermissionRepository,
  GroupRepository,
  MajorRepository,
  PermissionRepository,
  PersonaRepository,
  ProjectGalleryRepository,
  TeamMemberRepository,
  TeamRepository,
  TestimonialRepository,
  UserCommunityGroupRepository,
  UserGroupRepository,
  UserPermissionRepository,
  UserPersonaRepository,
  UserRepository,
} from '@app/domain/repositories';
import {
  AchievementRepositoryImpl,
  AuthRepositoryImpl,
  CommunityGroupAdminMemberRepositoryImpl,
  CommunityGroupAdminRepositoryImpl,
  CommunityGroupMemberRepositoryImpl,
  CommunityGroupRepositoryImpl,
  CompetitionInstanceRepositoryImpl,
  CompetitionOrganizerTypeRepositoryImpl,
  CompetitionOutputRepositoryImpl,
  CompetitionRankRepositoryImpl,
  CompetitionScaleRepositoryImpl,
  CompetitionTeamTypeRepositoryImpl,
  CompetitionTimeRangeRepositoryImpl,
  CompetitionRepositoryImpl,
  CoreTeamDivisionRepositoryImpl,
  CoreTeamMemberRepositoryImpl,
  CoreTeamRepositoryImpl,
  DegreeRepositoryImpl,
  FacultyRepositoryImpl,
  FundApplicationRepositoryImpl,
  GroupPermissionRepositoryImpl,
  GroupRepositoryImpl,
  MajorRepositoryImpl,
  PermissionRepositoryImpl,
  PersonaRepositoryImpl,
  ProjectGalleryRepositoryImpl,
  TeamMemberRepositoryImpl,
  TeamRepositoryImpl,
  TestimonialRepositoryImpl,
  UserCommunityGroupRepositoryImpl,
  UserGroupRepositoryImpl,
  UserPermissionRepositoryImpl,
  UserPersonaRepositoryImpl,
  UserRepositoryImpl,
} from '@app/infrastructure/repositories';
import { Container } from 'inversify';
import {
  AuthServerDataSource,
  authServerDataSourceImpl,
  InfinityApiDataSource,
  infinityApiDataSourceImpl,
} from '@app/infrastructure/datasources/server';
import {
  CreateAchievement,
  CreateCommunityGroup,
  CreateCommunityGroupAdmin,
  CreateCompetition,
  CreateCompetitionInstance,
  CreateCompetitionOrganizerType,
  CreateCompetitionOutput,
  CreateCompetitionRank,
  CreateCompetitionScale,
  CreateCompetitionTeamType,
  CreateCompetitionTimeRange,
  CreateCoreTeamDivision,
  CreateCoreTeam,
  CreateDegree,
  CreateFaculty,
  CreateFundApplication,
  CreateGroup,
  CreateMajor,
  CreatePermission,
  CreatePersona,
  CreateProjectGallery,
  CreateTeam,
  CreateTestimonial,
  CreateUserPermission,
  CreateUserPersona,
  DeleteCompetition,
  DeleteCompetitionInstance,
  DeleteUserPermission,
  DeleteUserPersona,
  GetCommunityGroup,
  GetAchievement,
  GetAchievements,
  GetCommunityGroupAdmin,
  GetCommunityGroupAdmins,
  GetCommunityGroups,
  GetCompetition,
  GetCompetitionInstance,
  GetCompetitionInstances,
  GetCompetitionOrganizerType,
  GetCompetitionOrganizerTypes,
  GetCompetitionOutput,
  GetCompetitions,
  GetCompetitionOutputs,
  GetCompetitionRank,
  GetCompetitionRanks,
  GetCompetitionScale,
  GetCompetitionScales,
  GetCompetitionTeamType,
  GetCompetitionTeamTypes,
  GetCompetitionTimeRange,
  GetCompetitionTimeRanges,
  GetCoreTeamDivision,
  GetCoreTeamDivisions,
  GetCoreTeam,
  GetCoreTeams,
  GetDegree,
  GetDegrees,
  GetFaculty,
  GetFaculties,
  GetFundApplication,
  GetFundApplications,
  GetGroup,
  GetGroups,
  GetGroupPermissions,
  GetMajor,
  GetMajors,
  GetPermission,
  GetPermissions,
  GetProjectGallery,
  GetProjectGalleries,
  GetPersona,
  GetPersonas,
  GetSession,
  GetTeam,
  GetTeams,
  GetTeamMembers,
  GetTestimonial,
  GetTestimonials,
  GetUser,
  GetUserPermissions,
  GetUserPermissionsWithToken,
  GetUserPersonas,
  GetUserCommunityGroups,
  GetUserGroups,
  GetUsers,
  GetUsersWithToken,
  UpdateAchievement,
  UpdateCommunityGroup,
  UpdateCommunityGroupAdmin,
  UpdateCompetition,
  UpdateCompetitionInstance,
  UpdateCompetitionOrganizerType,
  UpdateCompetitionOutput,
  UpdateCompetitionRank,
  UpdateCompetitionScale,
  UpdateCompetitionTeamType,
  UpdateCompetitionTimeRange,
  UpdateCoreTeamDivision,
  UpdateCoreTeam,
  UpdateDegree,
  UpdateFaculty,
  UpdateFundApplication,
  UpdateGroup,
  UpdateMajor,
  UpdatePermission,
  UpdatePersona,
  UpdateProjectGallery,
  UpdateTeam,
  UpdateTestimonial,
  Logout,
  GetCoreTeamMembers,
  GetCommunityGroupMembers,
  GetCoreTeamMember,
  GetCommunityGroupAdminMember,
  GetCommunityGroupAdminMembers,
} from '@app/application';
import { SYMBOLS } from '@config';

export const serverContainer = new Container();

// Use Cases
serverContainer.bind<CreateAchievement>(SYMBOLS.CreateAchievement).to(CreateAchievement);
serverContainer.bind<CreateCommunityGroup>(SYMBOLS.CreateCommunityGroup).to(CreateCommunityGroup);
serverContainer
  .bind<CreateCommunityGroupAdmin>(SYMBOLS.CreateCommunityGroupAdmin)
  .to(CreateCommunityGroupAdmin);
serverContainer.bind<CreateCompetition>(SYMBOLS.CreateCompetition).to(CreateCompetition);
serverContainer
  .bind<CreateCompetitionInstance>(SYMBOLS.CreateCompetitionInstance)
  .to(CreateCompetitionInstance);
serverContainer
  .bind<CreateCompetitionOrganizerType>(SYMBOLS.CreateCompetitionOrganizerType)
  .to(CreateCompetitionOrganizerType);
serverContainer
  .bind<CreateCompetitionOutput>(SYMBOLS.CreateCompetitionOutput)
  .to(CreateCompetitionOutput);
serverContainer
  .bind<CreateCompetitionRank>(SYMBOLS.CreateCompetitionRank)
  .to(CreateCompetitionRank);
serverContainer
  .bind<CreateCompetitionScale>(SYMBOLS.CreateCompetitionScale)
  .to(CreateCompetitionScale);
serverContainer
  .bind<CreateCompetitionTeamType>(SYMBOLS.CreateCompetitionTeamType)
  .to(CreateCompetitionTeamType);
serverContainer
  .bind<CreateCompetitionTimeRange>(SYMBOLS.CreateCompetitionTimeRange)
  .to(CreateCompetitionTimeRange);
serverContainer
  .bind<CreateCoreTeamDivision>(SYMBOLS.CreateCoreTeamDivision)
  .to(CreateCoreTeamDivision);
serverContainer.bind<CreateCoreTeam>(SYMBOLS.CreateCoreTeam).to(CreateCoreTeam);
serverContainer.bind<CreateDegree>(SYMBOLS.CreateDegree).to(CreateDegree);
serverContainer.bind<CreateFaculty>(SYMBOLS.CreateFaculty).to(CreateFaculty);
serverContainer
  .bind<CreateFundApplication>(SYMBOLS.CreateFundApplication)
  .to(CreateFundApplication);
serverContainer.bind<CreateGroup>(SYMBOLS.CreateGroup).to(CreateGroup);
serverContainer.bind<CreateMajor>(SYMBOLS.CreateMajor).to(CreateMajor);
serverContainer.bind<CreatePermission>(SYMBOLS.CreatePermission).to(CreatePermission);
serverContainer.bind<CreatePersona>(SYMBOLS.CreatePersona).to(CreatePersona);
serverContainer.bind<CreateProjectGallery>(SYMBOLS.CreateProjectGallery).to(CreateProjectGallery);
serverContainer.bind<CreateTeam>(SYMBOLS.CreateTeam).to(CreateTeam);
serverContainer.bind<CreateTestimonial>(SYMBOLS.CreateTestimonial).to(CreateTestimonial);
serverContainer.bind<CreateUserPermission>(SYMBOLS.CreateUserPermission).to(CreateUserPermission);
serverContainer.bind<CreateUserPersona>(SYMBOLS.CreateUserPersona).to(CreateUserPersona);
serverContainer.bind<GetAchievement>(SYMBOLS.GetAchievement).to(GetAchievement);
serverContainer.bind<GetAchievements>(SYMBOLS.GetAchievements).to(GetAchievements);
serverContainer
  .bind<GetCommunityGroupAdmin>(SYMBOLS.GetCommunityGroupAdmin)
  .to(GetCommunityGroupAdmin);
serverContainer
  .bind<GetCommunityGroupAdmins>(SYMBOLS.GetCommunityGroupAdmins)
  .to(GetCommunityGroupAdmins);
serverContainer
  .bind<GetCommunityGroupAdminMember>(SYMBOLS.GetCommunityGroupAdminMember)
  .to(GetCommunityGroupAdminMember);
serverContainer
  .bind<GetCommunityGroupAdminMembers>(SYMBOLS.GetCommunityGroupAdminMembers)
  .to(GetCommunityGroupAdminMembers);
serverContainer.bind<GetCommunityGroup>(SYMBOLS.GetCommunityGroup).to(GetCommunityGroup);
serverContainer.bind<GetCommunityGroups>(SYMBOLS.GetCommunityGroups).to(GetCommunityGroups);
serverContainer
  .bind<GetCommunityGroupMembers>(SYMBOLS.GetCommunityGroupMembers)
  .to(GetCommunityGroupMembers);
serverContainer.bind<GetCompetition>(SYMBOLS.GetCompetition).to(GetCompetition);
serverContainer
  .bind<GetCompetitionInstance>(SYMBOLS.GetCompetitionInstance)
  .to(GetCompetitionInstance);
serverContainer
  .bind<GetCompetitionInstances>(SYMBOLS.GetCompetitionInstances)
  .to(GetCompetitionInstances);
serverContainer
  .bind<GetCompetitionOrganizerType>(SYMBOLS.GetCompetitionOrganizerType)
  .to(GetCompetitionOrganizerType);
serverContainer
  .bind<GetCompetitionOrganizerTypes>(SYMBOLS.GetCompetitionOrganizerTypes)
  .to(GetCompetitionOrganizerTypes);
serverContainer.bind<GetCompetitionOutput>(SYMBOLS.GetCompetitionOutput).to(GetCompetitionOutput);
serverContainer.bind<GetCompetitions>(SYMBOLS.GetCompetitions).to(GetCompetitions);
serverContainer
  .bind<GetCompetitionOutputs>(SYMBOLS.GetCompetitionOutputs)
  .to(GetCompetitionOutputs);
serverContainer.bind<GetCompetitionRanks>(SYMBOLS.GetCompetitionRanks).to(GetCompetitionRanks);
serverContainer.bind<GetCompetitionRank>(SYMBOLS.GetCompetitionRank).to(GetCompetitionRank);
serverContainer.bind<GetCompetitionScale>(SYMBOLS.GetCompetitionScale).to(GetCompetitionScale);
serverContainer.bind<GetCompetitionScales>(SYMBOLS.GetCompetitionScales).to(GetCompetitionScales);
serverContainer
  .bind<GetCompetitionTeamType>(SYMBOLS.GetCompetitionTeamType)
  .to(GetCompetitionTeamType);
serverContainer
  .bind<GetCompetitionTeamTypes>(SYMBOLS.GetCompetitionTeamTypes)
  .to(GetCompetitionTeamTypes);
serverContainer
  .bind<GetCompetitionTimeRange>(SYMBOLS.GetCompetitionTimeRange)
  .to(GetCompetitionTimeRange);
serverContainer
  .bind<GetCompetitionTimeRanges>(SYMBOLS.GetCompetitionTimeRanges)
  .to(GetCompetitionTimeRanges);
serverContainer.bind<GetCoreTeamDivision>(SYMBOLS.GetCoreTeamDivision).to(GetCoreTeamDivision);
serverContainer.bind<GetCoreTeamDivisions>(SYMBOLS.GetCoreTeamDivisions).to(GetCoreTeamDivisions);
serverContainer.bind<GetCoreTeamMember>(SYMBOLS.GetCoreTeamMember).to(GetCoreTeamMember);
serverContainer.bind<GetCoreTeamMembers>(SYMBOLS.GetCoreTeamMembers).to(GetCoreTeamMembers);
serverContainer.bind<GetCoreTeam>(SYMBOLS.GetCoreTeam).to(GetCoreTeam);
serverContainer.bind<GetCoreTeams>(SYMBOLS.GetCoreTeams).to(GetCoreTeams);
serverContainer.bind<GetDegree>(SYMBOLS.GetDegree).to(GetDegree);
serverContainer.bind<GetDegrees>(SYMBOLS.GetDegrees).to(GetDegrees);
serverContainer.bind<GetFaculty>(SYMBOLS.GetFaculty).to(GetFaculty);
serverContainer.bind<GetFaculties>(SYMBOLS.GetFaculties).to(GetFaculties);
serverContainer.bind<GetFundApplication>(SYMBOLS.GetFundApplication).to(GetFundApplication);
serverContainer.bind<GetFundApplications>(SYMBOLS.GetFundApplications).to(GetFundApplications);
serverContainer.bind<GetGroup>(SYMBOLS.GetGroup).to(GetGroup);
serverContainer.bind<GetGroups>(SYMBOLS.GetGroups).to(GetGroups);
serverContainer.bind<GetGroupPermissions>(SYMBOLS.GetGroupPermissions).to(GetGroupPermissions);
serverContainer.bind<GetMajor>(SYMBOLS.GetMajor).to(GetMajor);
serverContainer.bind<GetMajors>(SYMBOLS.GetMajors).to(GetMajors);
serverContainer.bind<GetPermission>(SYMBOLS.GetPermission).to(GetPermission);
serverContainer.bind<GetPermissions>(SYMBOLS.GetPermissions).to(GetPermissions);
serverContainer.bind<GetProjectGallery>(SYMBOLS.GetProjectGallery).to(GetProjectGallery);
serverContainer.bind<GetProjectGalleries>(SYMBOLS.GetProjectGalleries).to(GetProjectGalleries);
serverContainer.bind<GetPersona>(SYMBOLS.GetPersona).to(GetPersona);
serverContainer.bind<GetPersonas>(SYMBOLS.GetPersonas).to(GetPersonas);
serverContainer.bind<GetSession>(SYMBOLS.GetSession).to(GetSession);
serverContainer.bind<GetTeam>(SYMBOLS.GetTeam).to(GetTeam);
serverContainer.bind<GetTeams>(SYMBOLS.GetTeams).to(GetTeams);
serverContainer.bind<GetTeamMembers>(SYMBOLS.GetTeamMembers).to(GetTeamMembers);
serverContainer.bind<GetTestimonial>(SYMBOLS.GetTestimonial).to(GetTestimonial);
serverContainer.bind<GetTestimonials>(SYMBOLS.GetTestimonials).to(GetTestimonials);
serverContainer.bind<GetUser>(SYMBOLS.GetUser).to(GetUser);
serverContainer
  .bind<GetUserCommunityGroups>(SYMBOLS.GetUserCommunityGroups)
  .to(GetUserCommunityGroups);
serverContainer.bind<GetUserGroups>(SYMBOLS.GetUserGroups).to(GetUserGroups);
serverContainer.bind<GetUserPermissions>(SYMBOLS.GetUserPermissions).to(GetUserPermissions);
serverContainer
  .bind<GetUserPermissionsWithToken>(SYMBOLS.GetUserPermissionsWithToken)
  .to(GetUserPermissionsWithToken);
serverContainer.bind<GetUserPersonas>(SYMBOLS.GetUserPersonas).to(GetUserPersonas);
serverContainer.bind<GetUsers>(SYMBOLS.GetUsers).to(GetUsers);
serverContainer.bind<GetUsersWithToken>(SYMBOLS.GetUsersWithToken).to(GetUsersWithToken);
serverContainer.bind<Logout>(SYMBOLS.Logout).to(Logout);
serverContainer.bind<DeleteCompetition>(SYMBOLS.DeleteCompetition).to(DeleteCompetition);
serverContainer
  .bind<DeleteCompetitionInstance>(SYMBOLS.DeleteCompetitionInstance)
  .to(DeleteCompetitionInstance);
serverContainer.bind<DeleteUserPermission>(SYMBOLS.DeleteUserPermission).to(DeleteUserPermission);
serverContainer.bind<DeleteUserPersona>(SYMBOLS.DeleteUserPersona).to(DeleteUserPersona);
serverContainer.bind<UpdateAchievement>(SYMBOLS.UpdateAchievement).to(UpdateAchievement);
serverContainer.bind<UpdateCommunityGroup>(SYMBOLS.UpdateCommunityGroup).to(UpdateCommunityGroup);
serverContainer
  .bind<UpdateCommunityGroupAdmin>(SYMBOLS.UpdateCommunityGroupAdmin)
  .to(UpdateCommunityGroupAdmin);
serverContainer.bind<UpdateCompetition>(SYMBOLS.UpdateCompetition).to(UpdateCompetition);
serverContainer
  .bind<UpdateCompetitionInstance>(SYMBOLS.UpdateCompetitionInstance)
  .to(UpdateCompetitionInstance);
serverContainer
  .bind<UpdateCompetitionOrganizerType>(SYMBOLS.UpdateCompetitionOrganizerType)
  .to(UpdateCompetitionOrganizerType);
serverContainer
  .bind<UpdateCompetitionOutput>(SYMBOLS.UpdateCompetitionOutput)
  .to(UpdateCompetitionOutput);
serverContainer
  .bind<UpdateCompetitionRank>(SYMBOLS.UpdateCompetitionRank)
  .to(UpdateCompetitionRank);
serverContainer
  .bind<UpdateCompetitionScale>(SYMBOLS.UpdateCompetitionScale)
  .to(UpdateCompetitionScale);
serverContainer
  .bind<UpdateCompetitionTeamType>(SYMBOLS.UpdateCompetitionTeamType)
  .to(UpdateCompetitionTeamType);
serverContainer
  .bind<UpdateCompetitionTimeRange>(SYMBOLS.UpdateCompetitionTimeRange)
  .to(UpdateCompetitionTimeRange);
serverContainer
  .bind<UpdateCoreTeamDivision>(SYMBOLS.UpdateCoreTeamDivision)
  .to(UpdateCoreTeamDivision);
serverContainer.bind<UpdateCoreTeam>(SYMBOLS.UpdateCoreTeam).to(UpdateCoreTeam);
serverContainer.bind<UpdateDegree>(SYMBOLS.UpdateDegree).to(UpdateDegree);
serverContainer.bind<UpdateFaculty>(SYMBOLS.UpdateFaculty).to(UpdateFaculty);
serverContainer
  .bind<UpdateFundApplication>(SYMBOLS.UpdateFundApplication)
  .to(UpdateFundApplication);
serverContainer.bind<UpdateGroup>(SYMBOLS.UpdateGroup).to(UpdateGroup);
serverContainer.bind<UpdateMajor>(SYMBOLS.UpdateMajor).to(UpdateMajor);
serverContainer.bind<UpdatePermission>(SYMBOLS.UpdatePermission).to(UpdatePermission);
serverContainer.bind<UpdatePersona>(SYMBOLS.UpdatePersona).to(UpdatePersona);
serverContainer.bind<UpdateProjectGallery>(SYMBOLS.UpdateProjectGallery).to(UpdateProjectGallery);
serverContainer.bind<UpdateTeam>(SYMBOLS.UpdateTeam).to(UpdateTeam);
serverContainer.bind<UpdateTestimonial>(SYMBOLS.UpdateTestimonial).to(UpdateTestimonial);

// Controllers
serverContainer.bind<AuthController>(SYMBOLS.AuthController).to(AuthControllerImpl);

// Repositories
serverContainer
  .bind<AchievementRepository>(SYMBOLS.AchievementRepository)
  .to(AchievementRepositoryImpl);
serverContainer.bind<AuthRepository>(SYMBOLS.AuthRepository).to(AuthRepositoryImpl);
serverContainer
  .bind<CommunityGroupAdminMemberRepository>(SYMBOLS.CommunityGroupAdminMemberRepository)
  .to(CommunityGroupAdminMemberRepositoryImpl);
serverContainer
  .bind<CommunityGroupAdminRepository>(SYMBOLS.CommunityGroupAdminRepository)
  .to(CommunityGroupAdminRepositoryImpl);
serverContainer
  .bind<CommunityGroupMemberRepository>(SYMBOLS.CommunityGroupMemberRepository)
  .to(CommunityGroupMemberRepositoryImpl);
serverContainer
  .bind<CommunityGroupRepository>(SYMBOLS.CommunityGroupRepository)
  .to(CommunityGroupRepositoryImpl);
serverContainer
  .bind<CompetitionInstanceRepository>(SYMBOLS.CompetitionInstanceRepository)
  .to(CompetitionInstanceRepositoryImpl);
serverContainer
  .bind<CompetitionOrganizerTypeRepository>(SYMBOLS.CompetitionOrganizerTypeRepository)
  .to(CompetitionOrganizerTypeRepositoryImpl);
serverContainer
  .bind<CompetitionOutputRepository>(SYMBOLS.CompetitionOutputRepository)
  .to(CompetitionOutputRepositoryImpl);
serverContainer
  .bind<CompetitionRankRepository>(SYMBOLS.CompetitionRankRepository)
  .to(CompetitionRankRepositoryImpl);
serverContainer
  .bind<CompetitionScaleRepository>(SYMBOLS.CompetitionScaleRepository)
  .to(CompetitionScaleRepositoryImpl);
serverContainer
  .bind<CompetitionTeamTypeRepository>(SYMBOLS.CompetitionTeamTypeRepository)
  .to(CompetitionTeamTypeRepositoryImpl);
serverContainer
  .bind<CompetitionTimeRangeRepository>(SYMBOLS.CompetitionTimeRangeRepository)
  .to(CompetitionTimeRangeRepositoryImpl);
serverContainer
  .bind<CompetitionRepository>(SYMBOLS.CompetitionRepository)
  .to(CompetitionRepositoryImpl);
serverContainer
  .bind<CoreTeamDivisionRepository>(SYMBOLS.CoreTeamDivisionRepository)
  .to(CoreTeamDivisionRepositoryImpl);
serverContainer
  .bind<CoreTeamMemberRepository>(SYMBOLS.CoreTeamMemberRepository)
  .to(CoreTeamMemberRepositoryImpl);
serverContainer.bind<CoreTeamRepository>(SYMBOLS.CoreTeamRepository).to(CoreTeamRepositoryImpl);
serverContainer.bind<DegreeRepository>(SYMBOLS.DegreeRepository).to(DegreeRepositoryImpl);
serverContainer.bind<FacultyRepository>(SYMBOLS.FacultyRepository).to(FacultyRepositoryImpl);
serverContainer
  .bind<FundApplicationRepository>(SYMBOLS.FundApplicationRepository)
  .to(FundApplicationRepositoryImpl);
serverContainer
  .bind<GroupPermissionRepository>(SYMBOLS.GroupPermissionRepository)
  .to(GroupPermissionRepositoryImpl);
serverContainer.bind<GroupRepository>(SYMBOLS.GroupRepository).to(GroupRepositoryImpl);
serverContainer.bind<MajorRepository>(SYMBOLS.MajorRepository).to(MajorRepositoryImpl);
serverContainer
  .bind<PermissionRepository>(SYMBOLS.PermissionRepository)
  .to(PermissionRepositoryImpl);
serverContainer.bind<PersonaRepository>(SYMBOLS.PersonaRepository).to(PersonaRepositoryImpl);
serverContainer
  .bind<ProjectGalleryRepository>(SYMBOLS.ProjectGalleryRepository)
  .to(ProjectGalleryRepositoryImpl);
serverContainer
  .bind<TeamMemberRepository>(SYMBOLS.TeamMemberRepository)
  .to(TeamMemberRepositoryImpl);
serverContainer.bind<TeamRepository>(SYMBOLS.TeamRepository).to(TeamRepositoryImpl);
serverContainer
  .bind<TestimonialRepository>(SYMBOLS.TestimonialRepository)
  .to(TestimonialRepositoryImpl);
serverContainer
  .bind<UserCommunityGroupRepository>(SYMBOLS.UserCommunityGroupRepository)
  .to(UserCommunityGroupRepositoryImpl);
serverContainer.bind<UserGroupRepository>(SYMBOLS.UserGroupRepository).to(UserGroupRepositoryImpl);
serverContainer
  .bind<UserPermissionRepository>(SYMBOLS.UserPermissionRepository)
  .to(UserPermissionRepositoryImpl);
serverContainer
  .bind<UserPersonaRepository>(SYMBOLS.UserPersonaRepository)
  .to(UserPersonaRepositoryImpl);
serverContainer.bind<UserRepository>(SYMBOLS.UserRepository).to(UserRepositoryImpl);

// Data sources
serverContainer.bind<AuthServerDataSource>(SYMBOLS.AuthDataSource).toDynamicValue(() => {
  const getUsers = serverContainer.get<GetUsersWithToken>(SYMBOLS.GetUsersWithToken);
  const getUserPermissionsWithToken = serverContainer.get<GetUserPermissionsWithToken>(
    SYMBOLS.GetUserPermissionsWithToken,
  );
  return authServerDataSourceImpl(getUsers, getUserPermissionsWithToken);
});
serverContainer
  .bind<InfinityApiDataSource>(SYMBOLS.InfinityApiDataSource)
  .toConstantValue(infinityApiDataSourceImpl);
